blank_issues_enabled: false
contact_links:
  - name: 💬 Diskusi Komunitas DRG
    url: https://github.com/ardyniech/DRG-APK/discussions
    about: Ajukan pertanyaan umum seputar komunitas Driver Riang Gembira.
