package com.example.core.repository

import com.example.shared.models.*

object SeedData {
    fun getInitialMembers(): List<DriverMember> = listOf(
        DriverMember(
            id = "DRG-001",
            name = "Bambang Pamungkas",
            driverId = "DRG-001-KTA",
            phone = "081298765431",
            role = MemberRole.KETUA,
            motorcyclePlate = "N 4321 SJK",
            motorcycleModel = "Honda Vario 160",
            rating = 4.95f,
            reviewCount = 28,
            loyaltyPoints = 420,
            loyaltyTier = "Pahlawan Jalanan",
            verificationStatus = VerificationStatus.VERIFIED,
            screeningNotes = "Pendiri & Pengayom Komunitas. Integritas A+",
            isOnline = true,
            currentStatus = "Siaga Pantau",
            currentLat = -7.9839,
            currentLng = 112.6214,
            baseArea = "Klojen, Malang"
        ),
        DriverMember(
            id = "DRG-002",
            name = "Hendra Satrio",
            driverId = "DRG-002-KTA",
            phone = "081311223344",
            role = MemberRole.WAKIL_KETUA,
            motorcyclePlate = "N 3890 TGB",
            motorcycleModel = "Yamaha NMAX 155",
            rating = 4.90f,
            reviewCount = 21,
            loyaltyPoints = 380,
            loyaltyTier = "Pahlawan Jalanan",
            verificationStatus = VerificationStatus.VERIFIED,
            screeningNotes = "Koordinator Lapangan & Hubungan Antar Komunitas",
            isOnline = true,
            currentStatus = "Sedang Narik",
            currentLat = -7.9425,
            currentLng = 112.6150,
            baseArea = "Lowokwaru, Malang"
        ),
        DriverMember(
            id = "DRG-003",
            name = "Rian Pratama",
            driverId = "DRG-003-KTA",
            phone = "081555667788",
            role = MemberRole.SEKRETARIS,
            motorcyclePlate = "N 6543 KLU",
            motorcycleModel = "Honda Beat Deluxe",
            rating = 4.88f,
            reviewCount = 19,
            loyaltyPoints = 310,
            loyaltyTier = "Road Captain",
            verificationStatus = VerificationStatus.VERIFIED,
            screeningNotes = "Admin Registrasi, Data Anggota & Dokumentasi",
            isOnline = true,
            currentStatus = "Standby Posko",
            currentLat = -7.9620,
            currentLng = 112.6450,
            baseArea = "Blimbing, Malang"
        ),
        DriverMember(
            id = "DRG-004",
            name = "Siti Nurhaliza",
            driverId = "DRG-004-KTA",
            phone = "081987654321",
            role = MemberRole.BENDAHARA,
            motorcyclePlate = "N 5412 ERT",
            motorcycleModel = "Yamaha Fazzio 125",
            rating = 4.92f,
            reviewCount = 24,
            loyaltyPoints = 340,
            loyaltyTier = "Road Captain",
            verificationStatus = VerificationStatus.VERIFIED,
            screeningNotes = "Pengelola Kas Transparan DRG, pembukuan rapi",
            isOnline = true,
            currentStatus = "Sedang Narik",
            currentLat = -7.9950,
            currentLng = 112.6180,
            baseArea = "Sukun, Malang"
        ),
        DriverMember(
            id = "DRG-005",
            name = "Anton Wijaya (Satgas)",
            driverId = "DRG-005-KTA",
            phone = "082199887766",
            role = MemberRole.SATGAS,
            motorcyclePlate = "N 1109 SAT",
            motorcycleModel = "Honda ADV 160",
            rating = 4.96f,
            reviewCount = 35,
            loyaltyPoints = 460,
            loyaltyTier = "Satgas Elit",
            verificationStatus = VerificationStatus.VERIFIED,
            screeningNotes = "Ketua Tim Tanggap Darurat & Kawal Jalur Rawan",
            isOnline = true,
            currentStatus = "Patroli Jalur",
            currentLat = -7.8732,
            currentLng = 112.5276,
            baseArea = "Batu"
        ),
        DriverMember(
            id = "DRG-006",
            name = "Budi Santoso",
            driverId = "DRG-006-KTA",
            phone = "081700112233",
            role = MemberRole.DEWAN_ETIKA,
            motorcyclePlate = "N 2024 ETK",
            motorcycleModel = "Honda PCX 160",
            rating = 4.94f,
            reviewCount = 30,
            loyaltyPoints = 390,
            loyaltyTier = "Road Captain",
            verificationStatus = VerificationStatus.VERIFIED,
            screeningNotes = "Pengawas Disiplin, Screening Rekrutmen & Mediasi",
            isOnline = true,
            currentStatus = "Standby Posko",
            currentLat = -7.8935,
            currentLng = 112.6620,
            baseArea = "Singosari, Malang"
        ),
        DriverMember(
            id = "DRG-007",
            name = "Agus Supriadi",
            driverId = "DRG-007-KTA",
            phone = "085612345678",
            role = MemberRole.ANGGOTA,
            motorcyclePlate = "N 4567 POI",
            motorcycleModel = "Honda Vario 125",
            rating = 4.82f,
            reviewCount = 15,
            loyaltyPoints = 210,
            loyaltyTier = "Road Captain",
            verificationStatus = VerificationStatus.VERIFIED,
            screeningNotes = "Driver aktif 3 tahun, loyalitas tinggi",
            isOnline = true,
            currentStatus = "Sedang Narik",
            currentLat = -8.0120,
            currentLng = 112.6350,
            baseArea = "Kedungkandang, Malang"
        ),
        DriverMember(
            id = "DRG-008",
            name = "Fajar Nugraha",
            driverId = "DRG-REG-008",
            phone = "087811224466",
            role = MemberRole.ANGGOTA,
            motorcyclePlate = "N 7890 MNQ",
            motorcycleModel = "Yamaha Aerox 155",
            rating = 0.0f,
            reviewCount = 0,
            loyaltyPoints = 20,
            loyaltyTier = "Junior Rider",
            verificationStatus = VerificationStatus.PENDING_SCREENING,
            screeningNotes = "Calon anggota baru. Berkas SIM/STNK/KTP lengkap, menunggu verifikasi Admin & Dewan Etika",
            isOnline = false,
            currentStatus = "Menunggu Screening",
            currentLat = -7.9550,
            currentLng = 112.6100,
            baseArea = "Dinoyo, Malang"
        )
    )
}
